services:
  php-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: checkin_php
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - mysql-db
    networks:
      - checkin-net

  mysql-db:
    image: mysql:8.0.43-debian
    container_name: checkin_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: checkin_db
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - checkin-net

volumes:
  db_data:

networks:
  checkin-net:
    driver: bridge
